Repository aalhour/C-Sharp-Algorithms, pull requests merged in 2019-11, with the labels that each got.

#82 Fix RedBlackTree impl/test #81
  DataStructures/Trees/BinarySearchTreeNode.cs
  DataStructures/Trees/RedBlackTree.cs
  UnitTest/DataStructuresTests/RedBlackTreeTest.cs
Labels: bug

#115 Move Community Templates under .github directory
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/ALGORITHM_REQUEST.md
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/DATA_STRUCTURE_REQUEST.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  CONTRIBUTING.md
  README.md
Labels: feature

#113 #88 - WeightedEdge.IsWeighted should return true (#88)
  .gitignore
  DataStructures/Graphs/WeightedEdge.cs
Labels: bug

#119 Search algo
  Algorithms/Search/BinarySearcher.cs
  UnitTest/AlgorithmsTests/BinarySearcherTest.cs
Labels: algorithm request

#103 Added CircularBuffer DataStructure.
  DataStructures/Lists/CircularBuffer.cs
  UnitTest/DataStructuresTests/CircularBufferTest.cs
Labels: data structure request

#122 Implement basic Build and Test GitHub Workflow
  .github/workflows/build_and_test.yml
Labels: feature

#124 Turned the primes document into an embedded resource.
  DataStructures/Common/PrimesList.cs
  DataStructures/DataStructures.csproj
  UnitTest/DataStructuresTests/PrimeListTest.cs
Labels: feature
