Repository aalhour/C-Sharp-Algorithms, pull requests merged in 2019-10, with the labels that each got.

#86 Fixed #84 MaxHeap bad algorithm
  DataStructures/Heaps/BinaryMaxHeap.cs
  DataStructures/Heaps/BinaryMinHeap.cs
  UnitTest/DataStructuresTests/BinaryHeapsTest.cs
Labels: enhancement

#92 #91 - Updated Sieve of Eratosthenes to utilize Hashset instead of list inte…
  Algorithms/Numeric/SieveOfEratosthenes.cs
  UnitTest/AlgorithmsTests/SieveOfEratosthenesTests.cs
Labels: enhancement

#109 Added the contributors graph image using contributors-img app
  README.md
Labels: feature

#75 Proposed fixes for catalan numbers
  Algorithms/Numeric/BinomialCoefficients.cs
  Algorithms/Numeric/CatalanNumbers.cs
  UnitTest/AlgorithmsTests/CatalanNumbersTest.cs
Labels: optimization
